apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: world-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: worldkim
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/sstptkdss1/world-ops02'
    targetRevision: main
    path: . # 최상위 디렉토리를 참조하여 backend, frontend를 포함
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
